
version: "3"


services:

        jam-js-default:

                build: .

                container_name: jam-js-default

                ports:

                        - "6700:6700"

                volumes:
                        - "./usercontent.js:/tmp/usercontent.js"
                        - "./usercontent.input:/tmp/usercontent.input"
                        - "./home:/home"
