
version: "3"


services:

        jam-java-default:

                build: .

                container_name: jam-java-default

                ports:

                        - "6700:6700"

                volumes:
                        - "./usercontent.java:/tmp/usercontent.java"
                        - "./usercontent.input:/tmp/usercontent.input"
                        - "./home:/home"
